services:
  validator:
    image: gamedata-validator
    env_file: .env
    restart: unless-stopped
    user: 1012:1012
    stdin_open: true
    tty: true
    volumes:
      - ./output:/app/output
      - ./cache:/app/cache
